# Generated by Django 6.0.6 on 2026-06-23 07:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='created_time_of_comapny')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid_of_comany')),
                ('company_name', models.CharField(max_length=255, unique=True, verbose_name='name_of_company')),
                ('company_type', models.CharField(choices=[('TECH', 'Technology'), ('FIN', 'Finance'), ('BIO', 'Biotechnology')], max_length=10)),
            ],
        ),
    ]
