# Generated by Django 6.0.6 on 2026-06-23 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 23, 8, 48, 52, 348963), verbose_name='latest_updated_time'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_time_of_comapny'),
        ),
    ]
