# Generated by Django 6.0.6 on 2026-06-23 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_admin', '0002_company_updated_at_alter_company_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='latest_updated_time'),
        ),
    ]
