# Generated by Django 6.0.6 on 2026-06-23 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_admin', '0003_rename_company_name_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='latest_updated_time'),
        ),
    ]
