# Generated by Django 6.0.6 on 2026-06-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_admin', '0004_alter_company_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified_compnay'),
        ),
    ]
