# Generated by Django 5.2.6 on 2026-06-25 03:27

from django.db import migrations


def update_companies(apps, schema_editor):
    schema_editor.execute(
        "UPDATE digi_admin_company SET verified = FALSE"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('digi_admin', '0005_company_verified'),
    ]

    operations = [
        migrations.RunPython(update_companies)

    ]
