# Generated by Django 5.2.6 on 2026-06-25 06:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_admin', '0006_auto_20260625_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='department_id')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='department_name')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digi_admin.company')),
            ],
        ),
    ]
