# Generated by Django 5.2.6 on 2026-06-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_admin', '0007_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description of departments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
