# Generated by Django 5.2.6 on 2026-06-25 06:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_admin', '0008_department_description_of_departments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Companies',
        ),
        migrations.RenameModel(
            old_name='Department',
            new_name='Departments',
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name of employee', models.CharField(max_length=255, unique=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digi_admin.departments')),
            ],
        ),
    ]
