# Generated by Django 5.2.6 on 2026-06-25 07:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_admin', '0009_rename_company_companies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='department_id',
            new_name='department',
        ),
        migrations.AddField(
            model_name='employees',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='joined_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='joining date of employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digi_admin.employees'),
        ),
        migrations.AddField(
            model_name='employees',
            name='salary',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
