# Generated by Django 5.2.6 on 2026-06-25 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_admin', '0010_rename_company_id_departments_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
