# Generated by Django 6.0.6 on 2026-06-25 09:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_admin', '0011_departments_created_at_departments_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('website', models.URLField()),
                ('metadata', models.JSONField(default=dict)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='description of departments',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='name of employee',
        ),
        migrations.AddField(
            model_name='departments',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description of departments'),
        ),
        migrations.AddField(
            model_name='employees',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='name of employee'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ip_address', models.GenericIPAddressField(editable=False, protocol='ipV6')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digi_admin.employees')),
            ],
        ),
    ]
