# Generated by Django 6.0.6 on 2026-06-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_admin', '0012_employeeproject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='ip_address',
            field=models.GenericIPAddressField(protocol='ipV6'),
        ),
    ]
