# Generated by Django 6.0.6 on 2026-06-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_admin', '0013_alter_users_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
