# Generated by Django 6.0.6 on 2026-06-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_admin', '0014_alter_users_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeproject',
            name='employees',
            field=models.ManyToManyField(related_name='projects', to='digi_admin.employees'),
        ),
    ]
