# Generated by Django 6.0.6 on 2026-06-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_admin', '0015_employeeproject_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='joined_date',
            field=models.DateField(verbose_name='joining date of employee'),
        ),
    ]
