# Generated by Django 6.0.6 on 2026-06-25 11:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_admin', '0016_alter_employees_joined_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='departments',
            options={'ordering': ['company', 'name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ['name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddIndex(
            model_name='companies',
            index=models.Index(fields=['name'], name='digi_admin__name_35fd4f_idx'),
        ),
        migrations.AddIndex(
            model_name='companies',
            index=models.Index(fields=['verified'], name='digi_admin__verifie_70096b_idx'),
        ),
        migrations.AddIndex(
            model_name='companies',
            index=models.Index(fields=['company_type'], name='digi_admin__company_194795_idx'),
        ),
        migrations.AddIndex(
            model_name='departments',
            index=models.Index(fields=['name'], name='digi_admin__name_2c2fae_idx'),
        ),
        migrations.AddIndex(
            model_name='employees',
            index=models.Index(fields=['name'], name='digi_admin__name_127a30_idx'),
        ),
    ]
