# Generated by Django 6.0.6 on 2026-06-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_admin', '0017_alter_companies_options_alter_departments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeproject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
