# Generated by Django 6.0.6 on 2026-06-25 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_admin', '0018_alter_employeeproject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digi_admin.employees'),
        ),
    ]
