# Generated by Django 6.0.6 on 2026-06-25 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_admin', '0019_alter_employees_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
